---
- name: start ec2 instances
  hosts: localhost
  gather_facts: false
  vars:
       instance_ids:
                    - "i-020cb867221999471"
                    - "i-0bd179b194fce0f50"
                    - "i-0f4718d68bf6cbbfd"
                    - "i-0035871edbf85ffb6"
       region: "us-east-2"
  tasks:
        - name: start the sandbox instances
          amazon.aws.ec2_instance:
                instance_ids: "{{instance_ids}}"
                region: "{{region}}"
                state: running
                wait: true
                vpc_subnet_id: subnet-0a3f79dc2c077589e
