---
- name: new users to servers
  hosts: webservers
  become: true
  vars:
      ansible_user: root
      ansible_ssh_pass: Alto@800
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
     - name: adding new users  
       user:
            name: mallubr
            create_home: true
            shell: /bin/bash
            state: present
        

