---
- name: deployment of apache server
  hosts: offer_centos9:offer_ubuntu_24_04_lts
  become: true
  tasks:
     - name: webserver deployment
       package:
             name: httpd
             state: present
       when: ansible_os_family == "RedHat"

     - name: apache deployment Ubuntu
       package:
              name: apache2
              state: present
       when: ansible_os_family == "Debian"

     - name: copy the index file
       copy:
            src: index.html
            dest: /var/www/html
            mode: 0664
     - name: start the service
       service:
               name: httpd
               state: started
       when: ansible_os_family == "RedHat"

     - name: start service o Ubuntu
       service:
               name: apache2
               state: started
       when: ansible_os_family == "Debian"

     - name: enable the httpd service
       systemd:
                 name: httpd
                 enabled: true
       when: ansible_os_family == "RedHat"

     - name: enable the apache service
       systemd:
                 name: httpd
                 enabled: true
       when: ansible_os_family == "RedHat"       
