---
- name: deployment of apache server
  hosts: webservers
  become: true
  vars:
      ansible_user: root
      ansible_ssh_pass: Alto@800
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
     - name: webserver deployment
       package:
             name: httpd
             state: present
     - name: copy the index file
       copy:
            src: index.html
            dest: /var/www/html
            mode: 0664
     - name: start the service
       service:
               name: httpd
               state: started

     - name: enable the httpd service
       systemd:
                 name: httpd
                 enabled: true
